spring:
  # H2 config
  h2:
    console:
      enabled: true
      path: /h2
  # DataSource
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    platform: h2
    driver-class-name: org.h2.Driver


liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.xml
  enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    ru.zvyagintsev: DEBUG
  path: logs
  file: logs/SampleApp.log